# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!


target 'Project3' do
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase'
pod 'Firebase/Storage'
end

target 'Project3Tests' do

end

target 'Project3UITests' do

end

